### PR TITLE
Rename the trys variable to attempts

### PR DESCRIPTION
**Pull request by jbrooksuk**
This reads better.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Renaming a protected variable is technically a major breaking change.

**Comment by GrahamCampbell** [comment]
But....

**Comment by GrahamCampbell** [comment]
I made this class final, so we're probably good actually. ;)

**Comment by jbrooksuk** [comment]
:boom:

**Comment by GrahamCampbell** [comment]
This needed renaming in the locker class too btw.

**Comment by jbrooksuk** [comment]
I'll do that and push to `master`.

**Pull request merged**
