### PR TITLE
Fix exception when calling isMethodSafe() without arguments

### LINKED ISSUE #16: BadMethodCallException
Checking only for cacheable HTTP methods with Symfony\Component\HttpFoundation\Request::isMethodSafe()

called in LockingMiddleware.php

```
if ($request->isMethodSafe() || $this->shouldPassThrough($request)) {
       return $next($request);
}
```

--------------------------

Question: In what possible scenario are you using this package?

### PR DESCRIPTION
**Pull request by blitux**
Fix https://github.com/AltThree/Locker/issues/16

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Thanks for looking into this. So, just to be clear, in all versions of Symfony 3.x, 4.x and Symfony 5, when it's released, this mechanism for calling the method will work correctly?

That is, we need this to work on Symfony 3.4, 4.0, 4.1, 4.2, 4.3, 4.4, and 5.0.

**Comment by blitux** [comment]
It will work on 3.4 to 4.3. From 4.4 and beyond, it will trigger_error() a message, that shouldn't be a problem. I think in 5.0 the trigger_error() will be removed completely. 

See https://github.com/symfony/symfony/pull/31658/files#diff-9d63a61ac1b3720a090df6b1015822f2L1448

**Comment by GrahamCampbell** [comment]
Hmmm, I'd like to avoid any error being triggered.

**Comment by blitux** [comment]
The error will be triggered on 4.4 and above, which Laravel isn't using just yet (Laravel 5.8 is using symfony ^4.2). So, no errors will be triggered for now. Maybe, if you're supporting laravel 5.x using symfony 4.4+ you can release a new version that doesn't include this fix. Does that work for you?

**Comment by GrahamCampbell** [comment]
I think https://github.com/AltThree/Locker/pull/18 should do the job, in a way that should work on all versions, current and future. Please let me know what you think.

**Pull request closed without merging**
